name: Deploy
env:
  ENVIRONMENT : dev

on:
  push:
    branches: [ add-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: package
        run: |
            chmod 744 ./mvnw
            ./mvnw clean package -Dmaven.test.skip=true

      - name: build
        run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker build --build-arg APP_NAME=noti --build-arg ENVIRONMENT=$ENVIRONMENT -t sukkyun2/noti .

      - name: success
        run: echo 'success!'